version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todonet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tododb
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - todonet

volumes:
  pgdata:

networks:
  todonet:
